# Mixtures {#sec-mixed}

Perhaps the biggest difference between the decision theory found in game theory textbooks, and the one found in philosophy journals, concerns the status of mixed strategies. In the textbooks, mixed strategies are brought in almost without comment, or perhaps with a remark about their role in a celebrated theorem by @Nash1951. In philosophy journals, the possibility of mixed strategies is often dismissed almost as quickly.

The philosophers' dismissal is usually accompanied by one or both of the following two reasons.[^mix-1] First, Chooser might not be capable of carrying out a mixed strategy. They might not, for instance, have any coins in their pocket.[^mix-2] Second, Demon might punish people for randomising in some way, so the payouts will change. I'm going to argue that both reasons overgenerate. If they are reasons to reject mixed strategies, they are also reasons to reject the claim that agents have perfect knowledge of arithmetic. Since we do assume the latter, in decision theory agents take any bet on a true arithmetic claim at any odds, since all arithmetic truths have probability 1, we should also assume mixed strategies are permitted.

[^mix-1]: These reasons are both offered, briefly, by @Nozick1969, so they have a history in decision theory.

[^mix-2]: Not a particularly realistic concern when everyone carries a smartphone, but in theory smartphones might not exist.

It isn't obvious why choosers should be perfect at arithmetic. True, calculators are a real help, but not everyone has a calculator in their pocket. I argued in @sec-why-this-ideal that the reason we make this idealisation is that it is helpful for the explanatory tasks we usually use decision theory for. The uses of game theory suggest that allowing mixtures is a similarly helpful idealisation. Once it is noted that this is an idealisation, it doesn't matter that it isn't a realistic description of all people making decisions. Requiring realism, and in particular requiring that choosers have a realistic level of arithmetic ability, would destroy decision theory as we know it.

The thought that predictors might punish randomisation is even less conducive to decision theory as we know it. Think about the following problem. Chooser will be given a sequence of pairs of two digit numbers. They can reply by either saying a number, or saying "Pass". If they say a number, they get \$2 if it is the sum of those numbers, and nothing otherwise. If they pass, they get \$1. The catch is that if they are detected doing any mental arithmetic between hearing the numbers and saying something, they will be tortured. Decision theory as we know it has nothing to say about this case. Ideally, they simply say the right answer each time, and all the theories in the literature say that's the right thing to do. In practice, that's an absurd strategy. Chooser should utter the word "Pass" as often as they can, before they unintentionally do any mental arithmetic. The point is that as soon as we put constraints on how Chooser comes to act, and not just on what action Chooser performs, decision theory as we know it ceases to apply. And playing a mixed strategy is a way of coming to act. Punishing Chooser for it is like punishing Chooser for doing mental arithmetic, and is equally destructive to decision theory.[^mix-3]

[^mix-3]: It's important to remember here that we are doing idealised decision theory. My view is that idealised decision theory has nothing to say about cases where someone will be punished for doing mental arithmetic.

Perhaps you think my account of idealisation in @sec-ideal was wrong, and idealisations are really things we should be aiming for. This doesn't block the argument that ideal agents can play mixed strategies. Being able to carry out a mixed strategy is of practical value, especially when there are predictors around.[^mix-4] It's not good to lose every game of rock-paper-scissors to the nearest predictor. If some mental activity is of practical value, then being able to carry it out is a skill to do with practical rationality. The idealised agents in decision theory have all the skills to do with practical rationality. Hence they can carry out mixed strategies, since carrying them out is a skill to do with practical rationality. So I conclude that if we are idealising, and if that idealisation extends at least as far as arithmetic perfection, it should also extend to being able to carry out mixed strategies.

[^mix-4]: This point goes back at least to Oskar Morgenstern's discussion of the Holmes-Moriarty game (@Morgenstern1935).

That's not to say all decision theory should be idealised decision theory. We certainly need theories for real humans. Nor is it to say that decision theory for agents who can't perform mixed strategies is useless. For any set of idealisations, it could in principle be useful to work out what happens when you relax some of them from the model. The thing that is odd about contemporary philosophical decision theory, and the thing I've been stressing in this chapter, is that there should be some motivation for why one leaves some idealisations in place, and relaxes others. I don't see any theoretical or practical interest in working out decision theory for agents who are logically and mathematically perfect, but can't carry out mixed strategies. Such agents are not a lot like us; since we are not logically and mathematically perfect. And they aren't even particularly close to us; most people are better at carrying out unpredictable mixed strategies than they are at solving the optimisation problems they face in everyday life. That said, it's important to be cautious here. It's often hard to tell in advance which combinations of keeping these idealisations and relaxing those will be useful. Still, I haven't seen much use for the particular combination that most philosophers have landed on, and I'm not sure what use it even could have.

So from now on I'll assume (a) if two strategies are available, so is any mixed strategy built on them, and (b) if Chooser plays a mixed strategy, Demon can possibly predict that they play the mixed strategy, but not the output of it.
