# Ratificationist {#sec-ratify}

Solution concepts in game theory tend to be equilibria. When game theorists describe a situation as an equilibria, they mean that everyone is happy with their moves knowing what all the moves of all the players are. (Or, at least, they are as happy as they can be.) Put in decision theoretic terms, that means that all solutions are ratifiable. Any solution of a decision problem involves Chooser being happy with their choice once it is made. That is, if the correct theory says X is choiceworthy in a particular situation, it also says that X is choiceworthy conditional on being chosen.

## A Brief History of Ratificationism

Ratificationism, the view that the correct theory says all choices are ratifiable in this sense, used to be a more popular view among decision theorists. Richard @Jeffrey1983 added a ratifiability constraint to a broadly evidential decision theory. Ratifiability was endorsed by causal theorists such as @Weirich1985 and @Harper1986. It subsequently fell out of popularity, though it has been recently endorsed by @Fuscond. The loss of popularity was for two reasons.

One was the existence of cases where there is (allegedly) no ratifiable option. @tbl-no-pure is one such case.

|       | **PA** | **PB** |
|:-----:|:------:|:------:|
| **A** |   3    |   5    |
| **B** |   4    |   3    |

: A case with no pure ratifiable options. {#tbl-no-pure}

If Chooser plays A, they would prefer to play B. If Chooser plays B, they would prefer to play A. Things get worse if we add an option that is ratifiable, but unfortunate, as in @tbl-bad-third.

|       | **PA** | **PB** | **PX** |
|:-----:|:------:|:------:|:------:|
| **A** |   3    |   5    |   0    |
| **B** |   4    |   3    |   0    |
| **X** |   0    |   0    |   0    |

: A case with only a bad pure ratifiable option. {#tbl-bad-third}

The only ratifiable option is X, but surely it is worse than Up or Down. One might avoid this example by saying that there is a weak dominance constraint on rational choices, as well as a ratifiability constraint. But that won't help us much, as was pointed out by @Skyrms1984, since in @tbl-verybad-third there is no weakly dominant option, but X is surely still a bad play.

|       | **PA** | **PB** |    **PX**     |
|:-----:|:------:|:------:|:-------------:|
| **A** |   3    |   5    |       0       |
| **B** |   4    |   3    |       0       |
| **X** |   0    |   0    | $\varepsilon$ |

: Skyrms's counterexample to ratificationism. {#tbl-verybad-third}

A better option is to insist, as @Harper1986 did, and as I argued in @sec-mixed, that if Chooser is rational, they can play a mixed strategy. In all three of these games, the mixed strategy of (0.5 U, 0.5 D) will be ratifiable, as long as Chooser forms the belief (upon choosing to play this), that Demon will play the mixed strategy (1/3 U, 2/3 D). That's a sensible thing for Demon to play, since it is the only strategy that is ratifiable for Demon if Demon thinks Chooser can tell what they are going to do. And given Chooser's knowledge of Demon's goals, Chooser can tell what Demon is going to do once they choose.

So if mixed strategies are allowed, neither of the problems for ratifiability persist.

## Two Quick Arguments for Ratificationism.

Ratifiability is an intuitive constraint. There is something very odd about saying that such-and-such is a rational thing to do, but whoever does it will regret it the moment they act. If a theory does not endorse ratifiability, it feels like Chooser could have the following conversation with Theory. (In this example, Theory recommends X, but says it is better to have done Y conditional on having done X. If Theory does not comply with ratifiability, an example like this exists.)

| **Chooser**: I believe in you Theory, I'll do what you say.
| **Theory**: Do X!
| **Chooser**: Done.
| **Theory**: Oh no, you should have done Y.
| **Chooser**: Why didn't you say that earlier?
| **Theory**: Because earlier you hadn't done X.
| **Chooser**: But you told me to do X.
| **Theory**: I didn't know you would agree.
| **Chooser**: I said that I would.
| **Theory**: Er, I don't know what to say.

That's bad, and Theory should not sound like this.

It's also an important part of game theory that there really isn't a distinction between theorists and practitioners. A theorist can only say X is the right thing to do in situation S if someone actually in S could reason their way to doing X by following the exact same argument as the theorist uses to conclude that X is the right thing to do. That's impossible if (a) the theory rejects ratifiability, and (b) the person in S knows that they are going to follow the theory. Their conclusion that they will do X will be self-undermining, so they won't draw it. If the theorist draws it anyway, that violates the (rather attractive) idea that one can't draw more conclusions from outside a game than what an intelligent player could draw from inside the game.

## Ratifiability Without Mixtures

My defense of ratifiability made heavy use of mixed strategies. Could we defend ratifiability without appeal to mixed strategies? It's not a completely impossible task, but nor is it an appealing one.

@tbl-no-pure poses no serious problem. Without mixed strategies, the case is simply a dilemma. And we know that there are dilemmas in decision theory. Here's one familiar example. A sinner faces Judgment Day. Because of his sins, it is clear things will end badly for him. But he has done some good in his life, and that counts for something. The judge thinks he should get some days in the Good Place before being off to the Bad Place. But the judge can't decide how many. So the judge says to the sinner to pick a natural number *n*, and the sinner will spend *n* days in the Good Place, and then goodbye. This clearly is a dilemma; for any large *n*, saying *n*! would be considerably better.[^ratify-1] @Ahmed2012 says that it is an objection to a theory that it allows dilemmas in cases with finitely many options; dilemmas should only arise in infinite cases. But he doesn't really argue for this, and I can't see what an argument would be. Once you've allowed dilemmas of any kind, the door is open to all of them.

[^ratify-1]: Note that this is true even if days in heaven have diminishing marginal utility, so the dilemma can arise even if we work within bounded utility theory. This is not just the kind of problem, as discussed by @Goodsellnd, that arises in decision theory with unbounded utilities.

Nor does @tbl-bad-third pose a problem, since as I said, the ratifiability theorist could add a weak dominance constraint and turn Second table into another dilemma.

The problem is @tbl-verybad-third. There the ratifiability theorist who does not allow mixed strategies has to say that the case is an odd kind of Newcomb Problem, where the rational agent will predictably do badly. But it's a very odd Newcomb Problem; by choosing X the chooser didn't even make themselves better off. Indeed, they guaranteed the lowest payout in the game. I don't have a knock-down argument here, and maybe there is more to be said. This is where I think the argument for ratificationism really needs mixed strategies.
