# Rock-Paper-Scissors {#sec-rps}

This appendix shows how to find the equilibrium of @tbl-rps-modified, the version of Rock-Paper-Scissors where it is common knowledge that the players will get a bonus of *c* \> 0 if they will while playing rock. The game is symmetric, so we'll just work out Column's strategy, and the same will go for Row.

There is no pure strategy equilibrium of the game, so we have to find a mixed strategy for each player. And a mixed strategy equilibrium requires that every option that has positive probability has equal expected returns. (If that didn't happen, it wouldn't make sense to mix between them.) Let *x* be the probability (in equilibrium) that Column plays Rock, *y* that they play Paper, and *z* that they play Scissors. Given that, the expected return of the three options for Row are:

```{=tex}
\begin{align*}
V(Rock) &= z(1+c) - y \\
V(Paper) &= x - z \\
V(Scissors) &= y - x
\end{align*}
```
We know that these three values are equal, and that *x* + *y* + *z* = 1*.* Since *x* ‑ z = *y* ‑ *x*, it follows that *x* = $\frac{y+z}{2}$. And that plus the fact that *x* + *y* + *z* = 1 implies that *x* =  $\frac{1}{3}$. So we've already shown one of the surprising results; adding in the bonus *c* will not change the probability with which Rock is played. Substituting this value for *x* into the fact that Rock and Paper have the same payout, we get the following.

```{=tex}
\begin{align*}
&& \frac{1}{3} - z &= z(1+c) - y \\
\Rightarrow && \frac{1}{3} + y &= z(2+c) \\
\Rightarrow && z &= \frac{y + \frac{1}{3}}{2 + c}
\end{align*}
```
Now we can substitute the values for *x* and *z* into the fact that *x* + *y* + *z* = 1.

```{=tex}
\begin{align*}
&& x + y + z &= 1  && \\
\Rightarrow && \frac{1}{3} + y + \frac{y + \frac{1}{3}}{2 + c} &= 1 && \\
\Rightarrow && (2+c) + 3y(2+c) + (3y+1) &= 3(2+c) && \text{Multiply both sides by } 3(2+c) \\
\Rightarrow && 3cy + 9y + c + 3 &= 3c + 6 \\
\Rightarrow && 3cy + 9y &= 2c + 3 \\
\Rightarrow && y &= \frac{2c + 3}{3c + 9} \\
\Rightarrow && z &= \frac{3}{3c + 9} && \text{From previous derivation for }z
\end{align*}
```
So each option has expected payout $\frac{c}{3c+9}$. And there is one unsurprising result, namely that the expected return to the players increases as *c* increases. But note that *x*, the probability that a player plays Rock, is invariant as *c* changes. And *z*, the probability that a player plays Scissors, goes down as *c* goes up.

It is intuitive that announcing the reward makes each player less likely to play Scissors. And that in turn puts down downward pressure on playing Rock. What you need some theory (and algebra) to show is that this downward pressure is exactly as strong as the upward pressure that comes from the incentive for playing Rock supplied by the bystander. Intuition alone can tell you what the various forces are that are acting on a chooser; the role of theory is to say something more precise about the strength of these forces.
