# Against Uniqueness {#sec-unique}

In setting out GDT, I said that what mattered was that Chooser maximised expected utility given some credal function that was rational having made their choice. Some philosophers argue that the quantifier in the previous sentence is redundant; there is only one rational credence function one could have given some evidence. This view is known as Uniqueness, and its negation is known as Permissivism. The way I've stated GDT presupposes that Permissivism is correct, and I should defend that presupposition.

This appendix argues that thinking about symmetric games gives us new reason to believe in Permissivism. In keeping with the spirit of the book, the arguments will be game-theoretic. I'm going to offer two arguments, one involving finite games, and the other involving infinite games. In finite games, the theorist who denies Permissivism says that the players have to think that the other player is more likely to take one action rather than another, although they know the actions have equal expected utility. In infinite games, the theorist who denies Permissivism has to say that it is impossible for certain games to be played with common knowledge of rationality and shared evidence, although there does not seem to be anything paradoxical about the games. The latter set of arguments rely on the recent discovery that there are symmetric games with only asymmetric equilibria. It was long known that there are symmetric games with no pure strategy symmetric equilibria; the surprising new discovery is that there are symmetric games with asymmetric equilibria, but no symmetric equilibria involving either mixed or pure strategies. In both cases, thinking about players in symmetric games pushes us towards accepting Permissivism.

The Permissivist theses that have been the focus on recent philosophical attention vary along two dimensions.[^unique-1]

[^unique-1]: For a much more thorough introduction to the debate, and especially into the varieties of Permissivist theses, see @KopecTitelbaum2016 and @Meacham2019. The next three paragraphs draw heavily from these two papers. For more recent arguments in favour of Permissivism, see @Callahan2021, @Lota2023, @Palmira2023, and @Ye2023. For criticisms, see @Schultheis2018 and @Ross2021.

The first dimension concerns what we hold fixed when we say that multiple attitudes are rationally permissible. It's basically common ground that people with different evidence can rationally believe different things, or that a person can believe different things when their evidence changes. But are these sufficient conditions for rational disagreement or change also necessary conditions. What's called *Interpersonal Permissiveness* says that given some evidence, there may be more than one doxastic state that it is rational to be in.[^unique-2] What's called *Intrapersonal Permissiveness* says that given a person and some evidence, there may be more one doxastic state that it is rational to be in. A classic form of subjectivist Bayesianism says that a person can pick any prior they like, but they have to update it by conditionalisation. This is a version of a view that rejects Intrapersonal Permissiveness, since given one's prior there is only one permissible posterior, but endorses Interpersonal Permissiveness, since there are multiple permissible priors.

[^unique-2]: In setting up the debate, I'm following the standard practice and assuming some kind of evidentialism. If one thinks that other things than evidence matter to rational credence, such as thinking that testimony provides non-evidential reasons for belief, it is a little complicated but possible to restate everything here to fit such an epistemological view. The general picture is that 'evidence' here really means non-pragmatic reasons for belief. But it's simpler to say 'evidence', and that's what I'll generally say.

The second dimension concerns whether the distinct views can be acknowledged as rational. Stewart @Cohen2013 defends the view that multiple attitudes can be rational, but one cannot rationally acknowledge a distinct view as rational. Following @KopecTitelbaum2016, call a view that says multiple views can both be rationally held and be believed to be rational *Acknowledged Permissiveness*, and the view that says multiple views could be rationally held, but could not be acknowledged, *Unacknowledged Permissiveness*.

Putting the last two paragraphs together gives us four varieties of Permissive theses. The negation of a Permissive thesis is a Uniqueness thesis. The name suggests that there is precisely one rational attitude to take in a specified situation, but we'll interpret it as the view that there is at most one rational attitude to take so as to ensure each Uniqueness thesis is the negation of a Permissive thesis. So if there are four Permissive theses, there are four Uniqueness theses that negate them.

This appendix focuses on the strongest of these four Permissive theses, Acknowledged Intrapersonal Permissiveness, and its negation, Acknowledged Interpersonal Uniqueness. This is, I think, the most commonly discussed form of Permissiveness in the literature, and in any case is interesting. And I'm going to be arguing that in some cases involving symmetric games, coherence considerations provide a strong argument in favour of Acknowledged Intrapersonal Permissiveness.

The next two sections set out two symmetric games where Uniqueness[^unique-3] leads to surprising results. In all cases I'll assume that if Uniqueness is true, then the players know that it is true. And while this might be obvious, I'll also note explicitly that they players have no evidence about the game or the players beyond what I write about the structure of the games.

[^unique-3]: From now on, when I say 'Uniqueness' I mean Acknowledged Intrapersonal Uniqueness. It's easier to simply stipulate this now than repeating the phrase every time.

## Chicken

Some finite symmetric games don't have a symmetric pure-strategy equilibrium. One notable example is Chicken, one version of which is in @tbl-unique-chicken.

|            |   Stay    | Swerve |
|:----------:|:---------:|:------:|
|  **Stay**  | -100,-100 | 1, -1  |
| **Swerve** |   -1, 1   |  0, 0  |

: Chicken {#tbl-unique-chicken}

The symmetric pure-strategy pairs $\langle$ Stay, Stay $\rangle$ and $\langle$ Swerve, Swerve $\rangle$ are not equilibria; in each case both parties have an incentive to defect. But the game does have a symmetric mixed strategy equilibrium. It is that both players play the mixed strategy of Stay with probability 0.01, and Swerve with probability 0.99.

Now assume that Row and Column have the same relevant evidence, that they are self-aware and fully rational, and that these facts and no other are common knowledge between them, and that they are about to play Chicken one time. (It's also common knowledge that they won't play again; dropping this would raise the possibility of complicated strategic reasoning.)

Let **Swerve** be the proposition that a rational player with that evidence will Swerve. And call the players Row and Column. Given our assumptions so far, plus Uniqueness, we can prove that Row's credence in **Swerve** is 0.99. Here's the proof.

1.  Let *x* be Row's credence in **Swerve**.
2.  By self-awareness, Row knows that *x* is her credence in **Swerve**.
3.  Since Row knows Row is rational, Row can infer that *x* is a rational credence in **Swerve**.
4.  Since Row knows Uniqueness is true, Row can infer that *x* is the only rational credence in **Swerve**.
5.  Since Row knows Column is rational, Row can infer that *x* is Column's credence in **Swerve**, since (at step 4) Row has deduced that *x* is the only rational credence in **Swerve**.
6.  Since all the assumptions so far are common knowledge, Row can come to know that Column knows that *x* is Row's credence in **Swerve**.
7.  If *x* = 1, then Row can come to know that it is rational for Column to Swerve, while knowing that Row will also Swerve. But this is impossible, since if Column knows Row will Swerve, it is best for Column to Stay. So *x* ≠ 1.
8.  If *x* = 0, then Row can come to know that it is rational for Column to Stay, while knowing that Row will also Stay. But this is impossible, since if Column knows Row will Stay, it is best for Column to Swerve. So *x* ≠ 0.
9.  So 0 \< *x* \< 1.
10. Since Row knows Column's credence that Row will Swerve (as was shown at step 6), and Row knows Column is rational, but Row does not know what Column will do, it must be that Column is indifferent between Stay and Swerve given her (i.e., Column's) credences about what Row will do.[^unique-4]
11. Column is indifferent between Stay and Swerve only if her credence that Row will Swerve is 0.99. (This is a reasonably simple bit of algebra to prove.)
12. So from 10 and 11, Column's credence that Row will Swerve is 0.99.
13. By (known) Uniqueness, it follows that the only rational credence in **Swerve** is 0.99.
14. So since Row is rational, it follows that *x* = 0.99.

[^unique-4]: If Column was not indifferent between their options, the knowledge Row has by step 6 would be sufficient to deduce with certainty what Column will do. But at step 9 we showed that Row does not know what Column will do.

Now there is nothing inconsistent in this reasoning. In a sense, it is purely textbook reasoning. But the conclusion is deeply puzzling. We've proven that Column is indifferent between her two options. And we've proven that Row knows this. But we've also proven that Row thinks it is 99 times more likely that Column will choose one of the options over the other. Why is that? It isn't because there is more reason to do one than the other; given Column's attitudes, the options are equally balanced. It is purely because Uniqueness pushes us to a symmetric equilibrium, and this is the only symmetric equilibrium. Given Uniqueness, the only coherent state is to have believe the other party is 99 times more likely to resolve a tie one way rather than another.

It's important here that we're imagining a one-shot version of Chicken. If the game is played repeatedly, then it is natural that the players will tend to the equilibrium of the game. What is surprising is that Uniqueness pushes us to thinking that, if the rationality of the players is common knowledge, the mixed strategy Nash equilibrium will be played in a one-shot game. As Matthias @Risse2000 argues, the argument that mixed strategy Nash equilibria are rational requirements of one-shot games is very weak. But it's a conclusion the Uniqueness theorist is forced into.

It's even more puzzling because of another feature of Uniqueness. It's often very hard to see what the uniquely rational attitude could be in cases where the evidence is very sparse. The usual way to resolve this problem is to appeal to what @Keynes1921 dubbed the Principle of Indifference. That principle says, roughly, that if the evidence available for two options is equally good, treat them as equally likely. Here, Row thinks that Column is a utility maximiser who has two options of equal utility available to them. And Row concludes (and must conclude if Uniqueness is correct) that one of these options is 99 times more likely to be played. That's not inconsistent with the letter of the Principle of Indifference. But it is inconsistent with the spirit of it.

All that said, I suspect many defenders of Uniqueness will be happy to accept these conclusions. The next case is I think poses a deeper problem for them.

## Elections

The cases in this section come from some recent work on a rather old question,

> If a symmetric game has an equilibrium, does it have a symmetric equilibrium?

Over the years, a positive answer was given to various restricted forms of that question. Most importantly, John @Nash1951 showed that if each player has finitely many moves available, then the game does have a symmetric equilibrium.

But recently it has been proven that the answer to the general question is no. Mark @Fey2012 describes an example of a positive-sum two-player game that has only asymmetric equilibria.[^unique-5] Dimitrios @Xefteris2015 showed that there is a symmetric three-player zero-sum game that has only asymmetric equilibria. In fact, he showed that a very familiar game, a version of a Hotelling--Downs model of elections, has this property. Here's how he describes the game.

[^unique-5]: In Fey's game both players pick a real in \[0, 1\]. If both players pick numbers in (0, 1), the one who picks the larger number wins. But there are a lot of complications if one or both pick an extreme value, including the game not always being zero-sum. I'm not relying on it here because it is a little too close to the game I'll discuss at the end of this section where everyone agrees there is no way to play it given common knowledge of rationality. Fey's paper also includes a nice chronology of some of the proofs of positive answers to restricted forms of the question.

> Consider a unit mass of voters. Each voter is characterised by her ideal policy. We assume that the ideal policies of the voters are uniformly distributed in \[0, 1\]. We moreover assume that three candidates *A*, *B* and *C* compete for a single office. Each candidate *J* ∈ {*A*, *B*, *C*} announces a policy *s~J~* ∈ \[0, 1\] and each voter votes for the candidate who announced the policy platform which is nearest to her ideal policy. If a voter is indifferent between two or among all three candidates she evenly splits her vote between/among them. A candidate *J* ∈ {*A*, *B*, *C*} gets a payoff equal to one if she receives a vote-share strictly larger than the vote-share of each of the two other candidates. If two candidates tie in the first place each gets a payoff equal to one half. If all three candidates receive the same vote-shares then each gets a payoff equal to one third. In all other cases a candidate gets a payoff equal to zero. [@Xefteris2015, 124]

It is clear that there is no symmetric pure-strategy equilibrium here. If all candidates announced the same policy, everyone would get a payoff of $\frac{1}{3}$. But no matter what that strategy is, if *B* and *C* announce the same policy, then *A* has a winning move available. (If the number *B* and *C* say is not 0.5, *A* wins by saying 0.5. If they do both say 0.5, then *A* wins by saying 0.4.)

What's more surprising, and what Xefteris proves, is that there is no symmetric mixed strategy equilibria either. Again, in such an equilibrium, any player would have a payoff of $\frac{1}{3}$. Very roughly, the proof that no such equilibrium exists is that random deviations from the equilibrium are as likely to lead to winning as losing, so they have a payoff of roughly $\frac{1}{2}$. So there is no incentive to stay in the equilibrium. So no symmetric equilibrium exists.

Using this game, I'm going to offer the following argument for Uniqueness.

1.  It's possible that three people can play this (symmetric) game in a situation where it is commonly known that (a) each of them is rational, and (b) they have the same evidence. In the relevant sense of 'rational' a person is rational iff they have credences that are supported by their evidence, and they perform actions that maximise expected utility given their credences.
2.  If Uniqueness is true, then in a symmetric game where it is common knowledge that each person has the same evidence and is rational, every player will believe that the others have the same credences about what the others will do.
3.  If premise 2 is true, then if the players have the same evidence and are rational, the result of the game will be a symmetric equilibrium.
4.  The game does not have a symmetric equilibrium.
5.  So Uniqueness is false.

I'll go over this abstract argument, then apply it to the Xefteris game.

Premise 1 is a claim that a particular game, that has an equilibrium, is possible to play. There is a strong assumption that mathematically coherent games are indeed possible to play, so this feels like a safe enough assumption. I'll come back at the very end of the next section to whether it is safe.

Premise 2 is spelling out a consequence of Uniqueness, but it helps to go over why it is a consequence. Assume that player *x* has credence *p* that player *y* will play (pure) strategy *s*. In symbols, *Cr~x~*(*s~y~*) = *p*, where *Cr~x~* is *x*'s credence function, and *s~y~* is the proposition that *y* plays strategy *s*. By common knowledge of rationality, *x* thinks it is rational with their evidence to have credence *p* in *s~y~*. By Uniqueness, *x* thinks this is the only rational credence to have in *s~y~*. By common knowledge of sameness of evidence, *x* thinks that *y* is rational, and has the same evidence about *x* playing *s* as *x* has about *y* playing *s*. So *y* will do the only rational thing with that evidence, namely form credence *p* that *x* will play *s*. (In a game with more than two players, this also licences inferring that *y* believes that *z* will play *s* with probability *p*, and the same for all the other players.) Quite generally, *x* believes that *y* has the same credences about *x* as *x* themselves has about *y*.

Premise 3 says that this suffices for there to be a symmetric equilibrium of the game. In fact, we can say what that equilibrium would be: everyone plays the mixed strategy that corresponds to *x*'s credences about what *y* will play. By 'mixed strategy corresponding to these credences, I mean that if *Cr~x~*(*s~y~*) = *p*, then each player *y* in fact plays strategy *s* with probability *p*, and so on for all strategies, and probabilities.

Why is that strategy set, where everyone does what *x* thinks *y* will do, an equilibrium? It starts with the fact that premise 2, and the reasoning behind it, is all a priori. So it's knowable to a perfectly rational player, like *x*. So, if Uniqueness is true, *x* knows that whatever they think about the other players will (a) be true, and (b) be common knowledge. And since *x* takes the other players to be utility maximisers, that means that every strategy *x* gives them positive probability of playing must maximise expected utility given these (shared) credences about what everyone else will play. If there was some strategy that did not maximise expected utility, and *x* gave them positive probability of playing it, then *x* would think it was possible that the other player was not maximising expected utility, contradicting the assumption of common knowledge of rationality. That's to say, playing the mixed strategy that corresponds to *x*'s beliefs about *y* must be an equilibrium, if Uniqueness is true, and it is common knowledge that the players have the same evidence and are rational.

Premise 4 says that something which is entailed by Uniqueness, combined with the assumptions in premise 1 and the other two premises, is not in fact true. So by modus tollens, Uniqueness is not true.

The arguments about the first three premises should apply to any symmetric game, with common knowledge of rationality and shared evidence. In any such game, the credences any player has about any other should be convertible into a (possibly mixed) equilibrium of the game. That's because any player should be able to conclude that what they think about one player must be a rational belief (by the common knowledge of rationality), so must be the only rational belief given their own evidence (by Uniqueness), so must be the belief that everyone has (by shared evidence), so must in fact be correct (since it's the only rational belief, and they are rational), and since it is a correct belief, and everyone is in fact a utility maximiser while holding these (correct) beliefs about everyone, must be an equilibrium. So every symmetric game must have a symmetric equilibrium, if Uniqueness is true, and the game is played under conditions of common knowledge of rationality and shared evidence.

That's not true in this game. It does not in fact have a symmetric equilibrium. If we drop Uniqueness, it is easy enough to describe rational behaviour for players in this game. Here is one possible model for the game.

-   *A* plays 0.6 (and wins), *B* and *C* each play 0.4 (and lose).
-   Each player has a correct belief about what the other players will play.
-   But both *B* and *C* know they cannot win given the other player's moves, so they pick a move completely arbitrarily.
-   Further, each player has a correct belief about why each player makes the move they make.

This is the coherent equilibria that Xefteris describes, but it requires some amount of luck, since it requires that *B* and *C* pick 0.4 when they could pick absolutely anything. Here's a slightly more plausible model of the game.

-   *A* plays 0.6 (and wins), *B* and *C* each play 0.4 (and lose).
-   The only two rational plays are 0.4 and 0.6, and each of them is rationally permissible.
-   In any world that a player believes to be actual, or a player believes another player believes to be actual, or a player believes another player believes another player believes to be actual, etc., the following two conditions hold.
-   If a player plays 0.6, they believe the other two players will play 0.4, and hence playing 0.6 is a winning move.
-   If a player plays 0.4, they believe the other two players will play 0.6, and hence playing 0.4 is a winning move.

The main difference between this model and Xefteris's is that it allows that players have false beliefs. But why shouldn't they have false beliefs? All they know is that the other players are rational, and rationality (we're assuming) does not settle a unique verdict for what players will do. So I think this strategy set, where the players have rational (but false) beliefs about the other players, is more useful to think about.

## Objections

The arguments for premises 2 and 3 in the argument above assumed something slightly stronger than Uniqueness. They each assumed that each player knew Uniqueness was true, and could use that in their reasoning. (Most importantly, in the argument for premise 3, it's important that each player can reason through the reasoning behind premise 2, and that reasoning used Uniqueness.) What happens if we drop that assumption, and consider the possibility that Uniqueness is true but unknowable?

This possibility is a little uncomfortable for philosophical defenders of Uniqueness. If the players in these games do not know that Uniqueness is true, then neither do the authors writing about Uniqueness. And now we have to worry about whether it is permissible to assert in print that Uniqueness is true. I wouldn't make too much of this though. It is unlikely that a knowledge norm governs assertion in philosophical journals.

The bigger worry here is that one key argument for Uniqueness seems to require that Uniqueness is knowable. A number of recent authors have argued that Uniqueness best explains our practice of deferring to rational people.[^unique-6] For instance, Greco and Hedden use this principle in their argument for Uniqueness.

[^unique-6]: There is a nice discussion of this argument, including citations of the papers I'm about to discuss, in @KopecTitelbaum2016 [195].

> If agent *S*~1~ judges that *S*~2~'s belief that *P* is rational and that *S*~1~ does not have relevant evidence that *S*~2~ lacks, then *S*~1~ defers to *S*~2~'s belief that *P*. [@GrecoHedden2016, 373].

Similar kinds of arguments are made by @Dogramaci2012 and @Horowitz2014. But the principle looks rather dubious in the case of these games. Imagine that *A* forms a belief (we'll come back to how) that *B* believes that a rational thing to do in the Xefteris game is to play 0.6, and so believes that *B* will play 0.6. This last step requires Uniqueness, or, more specifically, *A*'s belief that *B* believes in Uniqueness. The reasoning is as follows. *A* thinks that *B* thinks that 0.6 is a rational move; so, by Uniqueness, *A* believes that *B* believes that 0.6 is the only rational move; so, by *B*'s belief in their own rationality, *B* believes that they will play 0.6; so, by *B*'s self-control as a practically rational agent, *B* will in fact play 0.6. Now *A* believes that they have the same evidence as *B*, and that a rational thing to do with that evidence is play 0.6. By Uniqueness, they will believe that the only rational thing for someone with the evidence that they have (and that *B* has) is to play 0.6. But that can't be right. If *B* is playing 0.6, as *A* has independently judged they will, the rational thing for *A* to do is to play something other than 0.6.

And that's the general case for these symmetric games with only asymmetric equilibria. Believing that someone else is at an equilibrium point is a reason to not copy them. Uniqueness, combined with common knowledge of shared evidence and rationality, implies that anyone who believes that another player will adopt strategy *s* has a reason to adopt strategy *s*. After all, another player is playing it, and since that player is rational it is a rational thing to do in their situation, so by common evidence it is a rational thing to do in one's own situation, so by Uniqueness it is the only rational thing to do in one's own situation. But since the symmetric situations are not equilibria, believing that the other person will do *s* cannot be a reason to do *s*. That means one of the three assumptions we made here - common knowledge of rationality, common knowledge of shared evidence, and Uniqueness, must be wrong. Since it is typically taken to be at least coherent to have common knowledge of rationality and common knowledge of shared evidence, it follows that Uniqueness is wrong.

But maybe the Uniqueness theorist could resist that last step. Maybe they could deny that the game, with the assumption of common knowledge of rationality and shared evidence, really is possible. [^unique-7] This perhaps isn't as surprising as it might seem.

[^unique-7]: This move won't really help with Chicken; but maybe in that case they can simply insist that a rational player will rationally think the other player is more likely to make one of the two choices with equal expected payoffs.

Note two things about the Xefteris game. First, it is an infinite game in the sense that each player has infinitely many choices. It turns out this matters to the proof that there is no symmetric equilibrium to the game. Second, we are assuming it is common knowledge, and hence true, that the players are perfectly rational. Third, we are assuming that perfect rationality entails that people will not choose one option when there is a better option available. When you put those three things together, some things that do not look obviously inconsistent turn out to be impossible. Here's one example of that.

> *A* and *B* are playing a game. Each picks a real number in the open interval (0, 1). They each receive a payoff equal to the average of the two numbers picked.

For any number that either player picks, there is a better option available. It is always better to pick $\frac{x+1}{2}$ than *x*, for example. So it is impossible that each player knows the other is rational, and that rationality means never picking one option when a better option is available.

So the Uniqueness theorist could say that the same thing is going on in the Xefteris game. Some infinitely games cannot be played by rational actors (understood as people who never choose sub-optimal options); this is one of them. But if this is all the Uniqueness theorist says, it is not a well motivated response. We can say why it is impossible to rationally play games like the open interval game; the options get better without end. But that isn't true in the Xefteris game. The only thing that makes the game seem impossible is the Uniqueness assumption. People who reject Uniqueness can easily describe how the Xefteris game can be played by rational players. Simply saying that it is impossible, without any motivation or explanation for this other than Uniqueness itself, feels like an implausible move.

## Conclusion

If Uniqueness is true, then the following thing happens in games between people who know each other to have the same evidence, and to be rational. When someone forms a belief about what the other person will do, they can infer that this is a rational way to play the game given knowledge that everyone else will do the same thing. But sometimes this is a very unintuitive inference. In Chicken, it implies that we should have asymmetric attitudes to someone who is facing a choice between two options with equal expected value. In the election game Xefteris describes, a game that feels consistent turns out to be impossible.

I think the conclusion to draw from these cases of symmetric interactions this is that Uniqueness is false, and hence Permissivism is true. Sometimes in such an interaction one simply has to form a belief about the other player, knowing they may well form a different belief about you. Indeed, sometimes only coherent way to form a belief about the other player is to believe that they will form a different belief about you. And that means giving up on Uniqueness.
